#!/usr/bin/env python3
"""
Aeronix AI Test Plan Generator
Automatically generates comprehensive test procedures for LoRa train car radios
"""

from pcb_parser import BOMParser, CoordinateParser, SchematicParser
from test_plan_generator import LoRaTestPlanGenerator, ArduinoTestGenerator
import sys
import os
import json

def main():
    print("🚂 === Aeronix AI Test Plan Generator ===")
    print("Automatic Test Procedure Generation for LoRa Train Car Radios\n")
    
    # File paths for provided documents
    config = {
        "lora_software_requirements": "input_data/lora_software_requirements.txt",
        "lora_hardware_requirements": "input_data/lora_hardware_requirements.txt", 
        "pcb_schematics": "input_data/PCB-Car-Radio.zip",
        "car_pcb_netlist": "input_data/Car-PCB_Netlist.txt",
        "car_pcb_bom": "input_data/Car-PCB_BOM.csv",
        "arduino_netlist": "input_data/Arduino_Uno_Netlist.txt",
        "arduino_bom": "input_data/Arduino_Uno_BOM.csv"
    }
    
    try:
        print("📋 Loading LoRa Radio Design Documents...")
        
        # Parse all input documents
        documents = load_design_documents(config)
        
        print("🤖 Generating AI Test Plans...")
        
        # Generate LoRa Radio Bring-Up Procedure
        print("\n🎯 Creating LoRa Bring-Up Procedure...")
        lora_generator = LoRaTestPlanGenerator(documents)
        lora_test_plan = lora_generator.generate_comprehensive_test_plan()
        
        # Generate Arduino Uno Test Case
        print("🔧 Creating Arduino Uno Test Case...")
        arduino_generator = ArduinoTestGenerator(documents)
        arduino_test_plan = arduino_generator.generate_arduino_test_procedure()
        
        # Output the generated test plans
        print("\n" + "="*70)
        print("📄 GENERATED TEST PROCEDURES")
        print("="*70)
        
        # Save LoRa test plan
        save_test_plan("LoRa_Bring_Up_Procedure.md", lora_test_plan)
        print("✅ LoRa Bring-Up Procedure saved to: LoRa_Bring_Up_Procedure.md")
        
        # Save Arduino test plan  
        save_test_plan("Arduino_Uno_Test_Procedure.md", arduino_test_plan)
        print("✅ Arduino Uno Test Procedure saved to: Arduino_Uno_Test_Procedure.md")
        
        # Display summary
        print(f"\n🎊 SUCCESS! Generated {len(lora_test_plan['test_steps'])} LoRa test steps")
        print(f"🎊 SUCCESS! Generated {len(arduino_test_plan['test_steps'])} Arduino test steps")
        
        # Show preview of generated procedures
        print("\n📋 LORA PROCEDURE PREVIEW:")
        print("-" * 40)
        for i, step in enumerate(lora_test_plan['test_steps'][:3], 1):
            print(f"{i}. {step['title']}")
            print(f"   {step['description'][:80]}...")
        
        print(f"\n📋 ARDUINO PROCEDURE PREVIEW:")
        print("-" * 40)  
        for i, step in enumerate(arduino_test_plan['test_steps'][:3], 1):
            print(f"{i}. {step['title']}")
            print(f"   {step['description'][:80]}...")
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return 1
    
    print(f"\n🚀 AI Test Plan Generation Complete!")
    print("Ready for hackathon demo! 🎯")
    return 0

def load_design_documents(config):
    """Load and parse all design documents"""
    documents = {
        'software_requirements': [],
        'hardware_requirements': [],
        'schematics': {},
        'bom_data': [],
        'netlist_data': [],
        'arduino_data': {}
    }
    
    # Load text requirements if available
    for req_type in ['lora_software_requirements', 'lora_hardware_requirements']:
        if os.path.exists(config[req_type]):
            with open(config[req_type], 'r') as f:
                documents[req_type.split('_')[1] + '_requirements'] = f.readlines()
    
    # Load BOM and netlist data
    bom_parser = BOMParser()
    if os.path.exists(config['car_pcb_bom']):
        documents['bom_data'] = bom_parser.parse_file(config['car_pcb_bom'])
    
    # Load coordinate/netlist data
    coord_parser = CoordinateParser()
    if os.path.exists(config['car_pcb_netlist']):
        documents['netlist_data'] = coord_parser.parse_file(config['car_pcb_netlist'])
    
    # Load Arduino data
    if os.path.exists(config['arduino_bom']):
        documents['arduino_data']['bom'] = bom_parser.parse_file(config['arduino_bom'])
    
    if os.path.exists(config['arduino_netlist']):
        documents['arduino_data']['netlist'] = coord_parser.parse_file(config['arduino_netlist'])
    
    return documents

def save_test_plan(filename, test_plan):
    """Save generated test plan to markdown file"""
    with open(f"output/{filename}", 'w') as f:
        f.write(f"# {test_plan['title']}\n\n")
        f.write(f"**Generated by:** Aeronix AI Test Plan Generator\n")
        f.write(f"**Target:** {test_plan['target_device']}\n")
        f.write(f"**Test Steps:** {len(test_plan['test_steps'])}\n\n")
        
        f.write("## Overview\n")
        f.write(f"{test_plan['overview']}\n\n")
        
        f.write("## Test Procedure\n\n")
        for i, step in enumerate(test_plan['test_steps'], 1):
            f.write(f"### Step {i}: {step['title']}\n")
            f.write(f"**Type:** {step['type']}\n")
            f.write(f"**Description:** {step['description']}\n")
            
            if 'expected_result' in step:
                f.write(f"**Expected Result:** {step['expected_result']}\n")
            
            if 'test_points' in step:
                f.write(f"**Test Points:** {', '.join(step['test_points'])}\n")
            
            if 'equipment' in step:
                f.write(f"**Required Equipment:** {', '.join(step['equipment'])}\n")
                
            f.write("\n---\n\n")

if __name__ == "__main__":
    # Create output directory
    os.makedirs("output", exist_ok=True)
    os.makedirs("input_data", exist_ok=True)
    
    sys.exit(main())